spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    platform: postgres
    url: jdbc:postgresql://tiny.db.elephantsql.com/bbgoeoxh
    username: bbgoeoxh
    password: ZKrgm-B4VSBt92fpVrBrZ0UtJok8wbQx
    driverClassName: org.postgresql.Driver


server:
  error:
    include-stacktrace: never



